include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    sort_constructors_first: false
    lines_longer_than_80_chars: false
    omit_local_variable_types: false
    prefer_single_quotes: true
    prefer_int_literals: false