name: demo_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  # The Flutter SDK.
  flutter:
    sdk: flutter
  # Used for date formatting.
  intl: ^0.19.0

dev_dependencies:
  # Provides the Flutter Localizations package.
  flutter_localizations:
    sdk: flutter
  flutter_test:
    sdk: flutter
  # Provides lint rules used internally at Very Good Ventures.
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/

  fonts:
    - family: Chicago
      fonts:
        - asset: fonts/Chicago.ttf