name: demo_app
description: "A Flutter project demonstrating integrations with Apple's Machine Learning frameworks."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  # The Flutter SDK.
  flutter:
    sdk: flutter
  # Used for date formatting.
  intl: ^0.19.0
  # Plugin for getting commonly used locations on host platform. In this example app, it is used
  # to get the path to the app's documents directory in order to provide images to the Swift
  # Vision plugin.
  path_provider: ^2.1.5

dev_dependencies:
  # Provides the Flutter Localizations package.
  flutter_localizations:
    sdk: flutter
  flutter_test:
    sdk: flutter
  # Provides lint rules used internally at Very Good Ventures.
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/vision_examples/
    - assets/sound_examples/

  fonts:
    - family: Chicago
      fonts:
        - asset: fonts/Chicago.ttf